### ISSUE TITLE
READ_PAIR_COUNT on hg38 reference

### ISSUE THREAD

**Issue by holtjma** [DecodeGenetics/read_haps#3]
Hello,

I'm trying to test the software on some samples, but I only get the FAIL and READ_PAIR_COUNT for my tests.  These samples (BAM and VCF) are definitely processed on hg38.  It seems to fail instantaneously.  Below is the command (full paths redacted):

```
[read_haps-0.2]$ ./read_haps -v -fa {redacted}/hg38.fa {redacted}/SL362490.bam {redacted}/read_haps/high_quality_markers_deCODE_2015.txt.gz {redacted}/SL362490.vcf.gz
parsed args 
read pos used file 
read VCF header 
SNP_PAIRS ERROR_PAIRS DOUBLE_ERROR_PAIR_COUNT DOUBLE_ERROR_FRACTION REL_ERROR_FRACTION NONSENSE_FRACTION PASS_FAIL REASON
0 0 0 0 0 0 FAIL READ_PAIR_COUNT
[read_haps-0.2]$ 
```

Thoughts on debugging the issue?

**Comment by bjarnivh** [comment]
I am pretty sure the problem is that you are giving the high quality markers as a .gz as input, but the program is assuming a plain text file, you need to gunzip the high quality marker set and the program should work.

**Comment by holtjma** [comment]
Ah, a silly mistake on my part.  That seems to have fixed it (or at least progressed the output), thanks for the quick response!

**Comment by DinahBack** [comment]
hi, i run ./read_haps --fa hg38.fa bqsr.bam high_quality_markers_deCODE_2015.txt genotyper.vcf.gz , and the value of the output log is 0: SNP_PAIRS ERROR_PAIRS DOUBLE_ERROR_PAIR_COUNT DOUBLE_ERROR_FRACTION REL_ERROR_FRACTION NONSENSE_FRACTION PASS_FAIL REASON
0 0 0 0 0 0 FAIL READ_PAIR_COUNT

**Comment by DinahBack** [comment]
Some head log is :parsed args
read pos used file
read VCF header
read pos used file
read VCF header
reading VCF file file chr1
reading VCF file file chr10
reading VCF file file chr11
reading VCF file file chr12
reading VCF file file chr13
reading VCF file file chr14
reading VCF file file chr15
reading VCF file file chr16
reading VCF file file chr17
reading VCF file file chr18
reading VCF file file chr19
reading VCF file file chr2
reading VCF file file chr20
reading VCF file file chr21
reading VCF file file chr22
reading VCF file file chr3
reading VCF file file chr4
reading VCF file file chr5
reading VCF file file chr6
reading VCF file file chr7
reading VCF file file chr8
reading VCF file file chr9
chr1 0
chr10 0
chr11 0
chr12 0
chr13 0
chr14 0
chr15 0
chr16 0
chr17 0
chr18 0
chr19 0
chr2 0
chr20 0
chr21 0
chr22 0
chr3 0
chr4 0
chr5 0
chr6 0
chr7 0
chr8 0
chr9 0
bam file scan chr1
reading Bam region chr1 1 248956422
added DP8480017159TRL1C048R02502139177
